### ISSUE TITLE
Should we use Firebase-UI?

### ISSUE THREAD

**Issue by jossiwolf** [flbaue/Android-Study-Jam#6]
There are [UI components provided by Firebase](https://github.com/firebase/FirebaseUI-Android), including an `Adapter` for the `RecyclerView`.

Should we use those?

I think it'd make it easier for everyone, but since we are teaching the basics of Android dev, it may be good to talk about (and use) things like `Adapters` yourself.

**Comment by flbaue** [comment]
Yes
